name: Deploy con Ansible
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
      - name: Ejecutar Despliegue (Solo tareas de Deploy)
        run: |
          ansible-playbook ansible/conf.yml \
            --connection=local \
            --limit localhost \
            --tags deploy \
            -e "app_db_url='${{ secrets.DATABASE_URL }}'" \
            -e "app_frontend_url='${{ secrets.FRONTEND_URL }}'" \
            -e "app_jwt_secret='${{ secrets.JWT_SECRET }}'" \
            -e "github_user='${{ github.repository_owner }}'" \
            -e "github_repo='${{ github.event.repository.name }}'"
