name: Deploy Backend

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1. Checkout en _work (obligatorio)
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Definir variables
      - name: Set vars
        run: echo "APP_DIR=/var/www/upTaskBackend" >> $GITHUB_ENV

      # 3. Crear carpeta si no existe
      - name: Crear directorio
        run: sudo mkdir -p $APP_DIR

      # 4. Permisos correctos
      - name: Permisos
        run: sudo chown -R $USER:$USER $APP_DIR

      # 5. Sync código (_work → /var/www)
      - name: Sync código
        run: rsync -az --delete ./ $APP_DIR

      # 6. Instalar dependencias
      - name: npm install
        run: npm install
        working-directory: ${{ env.APP_DIR }}

      # 7. Build
      - name: Build
        run: npm run build
        working-directory: $APP_DIR

      # 8. Variables de entorno
      - name: Crear .env
        run: |
          cat <<EOF > .env
          PORT=${{ vars.APP_PORT }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          FRONTEND_URL=${{ vars.FRONTEND_URL }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          EOF
        working-directory: $APP_DIR

      # 9. Migraciones DB
      - name: Prisma migrate
        run: npx prisma migrate deploy
        working-directory: $APP_DIR

      # 10. Reload app
      - name: PM2 reload
        run: |
          pm2 reload ecosystem.config.js --update-env || \
          pm2 start ecosystem.config.js --env production
        working-directory: $APP_DIR

      # 11. Guardar estado PM2
      - name: PM2 save
        run: pm2 save
