name: Deploy Backend

on:
  workflow_dispatch: # solo manual
  # push:
  #   branches: ["main"]
  #   paths:
  #     - "src/**" # solo si cambia el backend
  #     - "prisma/**"
  #     - "package*.json"
  #     - "ecosystem.config.js"

jobs:
  deploy:
    runs-on: self-hosted
    env:
      APP_DIR: /var/www/upTaskBackend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      #- name: Crear directorio
      #  run: sudo mkdir -p $APP_DIR

      - name: Permisos correctos
        run: sudo chown -R $USER:$USER $APP_DIR

      - name: Sync código (_work → /var/www)
        run: rsync -az --delete ./ $APP_DIR

      - name: Instalar dependencias
        run: npm ci
        working-directory: ${{ env.APP_DIR }}

      # - name: Build
      # run: npm run build
      # working-directory: ${{ env.APP_DIR }}

      - name: Crear variables de entorno - .env
        run: |
          cat <<EOF > .env
          PORT=${{ vars.APP_PORT }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          FRONTEND_URL=${{ vars.FRONTEND_URL }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          EOF
        working-directory: ${{ env.APP_DIR }}

      - name: Migraciones DB
        run: npx prisma migrate deploy
        working-directory: ${{ env.APP_DIR }}

      - name: Reload App con PM2
        run: |
          pm2 reload ecosystem.config.js --update-env || \
          pm2 start ecosystem.config.js --env production
        working-directory: ${{ env.APP_DIR }}

      - name: Guardar estado PM2
        run: pm2 save
